services:
  - type: web
    name: skin-disease-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
