services:
  - type: web
    name: skin-disease-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
